<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0-browser</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>CalcNova.Browser</AssemblyName>
    <RootNamespace>CalcNova.Browser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Browser" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../CalcNova.App/CalcNova.App.csproj" />
    <ProjectReference Include="../CalcNova.Currency/CalcNova.Currency.csproj" />
  </ItemGroup>
</Project>
