namespace CalcNova.App.Localization;

public enum AppStringKey
{
    AppName,
    Tagline,
    LocalFirst,

    ModeCalculator,
    ModeProgrammer,
    ModeCodePoint,
    ModeConverter,
    ModeStatistics,
    ModeEquations,
    ModeMatrices,
    ModeGraphing,
    ModeDateTime,
    ModeCurrency,
    ModeHistory,
    ModeSettings,
    ModeAbout,

    CalculatorTitle,
    CalculatorSubtitle,
    PromptEnterExpression,

    OnboardingWelcome,
    OnboardingCalculateTitle,
    OnboardingCalculateBody,
    OnboardingInputTitle,
    OnboardingInputBody,
    OnboardingPrivacyTitle,
    OnboardingPrivacyBody,
    OnboardingNoAccount,

    CurrencyTitle,
    CurrencyPrivacyBody,
    HistoryTitle,
    HistoryExportTitle,
    HistoryExportBody,
    SettingsLanguageReviewNote,
    AboutOpenSourceLicense,
    AboutSupportOptional,
    FooterLocalDefault,

    ActionEvaluate,
    ActionPasteExpression,
    ActionCopyResult,
    ActionConvert,
    ActionSwap,
    ActionAnalyze,
    ActionSolve,
    ActionCopy,
    ActionRefresh,
    ActionSave,
    ActionReset,
    ActionSkip,
    ActionStartCalculating,
    ActionRefreshRates,
    ActionFavorite,
    ActionDelete,
    ActionClearAll,
    ActionGenerateExportPreview,
    ActionCopyExport,
    ActionOpenRepository,
    ActionOpenGitHubProfile,

    LabelExpression,
    LabelResult,
    LabelAngleUnit,
    LabelWordSize,
    LabelSignificantDigits,
    LabelRecentPairs,
    LabelFavoritePairs,
    LabelTheme,
    LabelHistoryLimit,
    LabelLanguage,
    LabelDecimalPrecisionRange,
    LabelHistoryLimitRange,
    LabelBusiness,
    LabelSupport,

    PromptAmount,
    PromptFromIsoCode,
    PromptToIsoCode,
    PromptSearch,

    SettingEnableHistory,
    SettingGroupingSeparators,
    SettingHaptics,
    SettingReducedMotion,
    SettingHighContrast,

    StatusCopied,
    StatusReady,
    ErrorInvalidInput,
    ErrorClipboardUnavailable
}
